addition of margin-top in whoisNH section
naomis-novas/homepage pull request #61
Opened 2022-06-19 19:30 UTC by lucifertrj

## Description

Adding a margin-top above the avatar in whoisNH section.

## Related Issue

Missing Photo of Timiro and RavenclawFander

2022-06-19 20:56 UTC, nhcarrigan commented
Hi there! Could you explain the need for this change?

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Inefficient

2022-06-22 01:55 UTC, lucifertrj commented
> Hi there! Could you explain the need for this change?
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** question I have a question  |  **Tags:** Inefficient

There is no gap between the paragraph and margin, thus a few pixel margin top is added for the proper indentation.

2022-06-22 12:46 UTC, nhcarrigan requested changes

2022-06-22 12:46 UTC, nhcarrigan commented on index.html
> +          <img style="margin-top:20px;"
Rather than using an inline style, we should add a class or id and style it through the CSS file.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2023-01-02 04:14 UTC, naomi-lgbt commented
Closing as stale.

2023-01-02 04:14 UTC, closed without merging