a new design
naomis-novas/homepage pull request #67
Opened 2022-11-08 01:27 UTC by ngdream

a new design

2022-11-08 01:35 UTC, naomi-lgbt requested changes
Hey there! This is off to a very good start!

A few notes:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/63889819/200452148-6e74d67b-a3c1-4484-96eb-223e01470883.png">

We should stick with a purple background, IMHO.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/63889819/200452177-42e3668a-5569-436b-a548-c4b19d00345a.png">

Whatever background we use should stretch, not tile.

<img width="1908" alt="image" src="https://user-images.githubusercontent.com/63889819/200452226-0dadb2b3-d754-4de3-97a8-3ec645d6afff.png">

This section should have the same width.

2022-11-09 12:17 UTC, ngdream commented
hello @naomi-lgbt  i did some improvement

2022-11-09 14:37 UTC, naomi-lgbt requested changes

2022-11-09 14:37 UTC, naomi-lgbt commented on index.html
> +      <p>  <a href="" class="button">join community</a></p>
```suggestion
      <p>  <a href="https://github.com/naomis-novas/community/issues/new?assignees=naomi-lgbt&labels=%E2%9C%89%EF%B8%8F+misc%3A+invite+to+org&template=join_org.yml&title=%5BORG%5D+Invite+me+to+the+organization" class="button">join community</a></p>
```

Here's the invite link.

2022-11-09 15:25 UTC, naomi-lgbt approved these changes
banger pr, thanks for contributing!

2022-11-09 15:25 UTC, merged

2022-11-09 23:59 UTC, ngdream commented
cool