fixed-joincommunity button
naomis-novas/homepage pull request #70
Opened 2023-02-20 16:48 UTC by KaKashi1210

# Pull Request

## Description

Added hover effect on join community button for visual cue.

## Related Issue

Closes #69

2023-02-20 20:59 UTC, Panquesito7 submitted a review, later dismissed
LGTM. Thanks! 🚀

2023-02-20 21:25 UTC, KaKashi1210 commented
@Panquesito7 Thanks for taking out time to review the commit <3.

2023-02-20 21:26 UTC, naomi-lgbt requested changes
Nitpicking - but let's keep a blank line between style rules for readability

2023-02-20 21:26 UTC, naomi-lgbt commented on public/index.css
> +.button:hover{
```suggestion
}

.button:hover{
```

2023-02-20 21:28 UTC, KaKashi1210 commented
@naomi-lgbt done

2023-02-20 21:34 UTC, KaKashi1210 commented
do you want some other changes?

2023-02-20 21:36 UTC, naomi-lgbt approved these changes
banger pr, thanks for contributing!

2023-02-20 21:37 UTC, merged

2023-02-20 21:37 UTC, naomi-lgbt commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.naomi.lgbt)

2023-03-13 01:58 UTC, KaKashi1210 commented
Commenting here for holopin badge!